# Generated by Django 5.2 on 2025-04-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0002_delete_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=2)),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.IntegerField()),
                ('fuma', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('estatura', models.IntegerField()),
                ('antecedentes_medicos', models.TextField()),
                ('sintomas_generales', models.TextField()),
                ('enfermedad_predicha', models.CharField(max_length=100)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
